version: '3.7'


services:
  postgres:
    image: postgres:15
    container_name: psql-secret_app
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/db-init:/docker-entrypoint-initdb.d
    ports:
      - "${DB_OUTSIDE_PORT}:5432"
  
  redis:
    image: redis:7
    container_name: redis-secret_app
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_OUTSIDE_PORT}:6379"

  secret_app:
    build: .
    container_name: secret_app
    env_file:
      - ./.env
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - postgres
    command: 
      ["sh", "-c", "chmod +x docker/src.sh && docker/src.sh"]
volumes:
  postgres-data:
  redis-data: