"""empty message

Revision ID: 1de8ba2842a6
Revises: e6f7764cbe56
Create Date: 2025-04-08 01:07:41.391655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de8ba2842a6'
down_revision: Union[str, None] = 'e6f7764cbe56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secret_logs', 'secret_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secret_logs', 'secret_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
