"""empty message

Revision ID: 841beab15a83
Revises: 1de8ba2842a6
Create Date: 2025-04-08 08:46:00.718079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841beab15a83'
down_revision: Union[str, None] = '1de8ba2842a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.drop_column('secrets', 'is_readed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets', sa.Column('is_readed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('secrets', 'is_read')
    # ### end Alembic commands ###
