"""empty message

Revision ID: 8d8c7b8268b5
Revises: 
Create Date: 2025-04-07 23:52:48.535652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8c7b8268b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secrets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('secret', sa.LargeBinary(), nullable=False),
    sa.Column('is_readed', sa.Boolean(), nullable=False),
    sa.Column('passphrase', sa.LargeBinary(), nullable=True),
    sa.Column('ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secret_logs',
    sa.Column('event_type', sa.Enum('CREATE', 'READ', 'DELETE', name='actiontype', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('secret_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['secret_id'], ['secrets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret_logs')
    op.drop_table('secrets')
    # ### end Alembic commands ###
