"""empty message

Revision ID: ca757f479e98
Revises: 8d8c7b8268b5
Create Date: 2025-04-07 23:56:29.065762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca757f479e98'
down_revision: Union[str, None] = '8d8c7b8268b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret_logs', sa.Column('action_type', sa.Enum('CREATE', 'READ', 'DELETE', name='actiontype', native_enum=False), nullable=False))
    op.drop_column('secret_logs', 'event_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret_logs', sa.Column('event_type', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.drop_column('secret_logs', 'action_type')
    # ### end Alembic commands ###
