from core.exceptions import AppError


class SecretError(AppError): ...


class SecretNotFoundError(SecretError): ...


class SecretExpiredError(SecretError): ...


class SecretAlreadyReadError(SecretError): ...


class SecretPassphraseError(SecretError): ...
